//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSHTunnel4Win.Resources;

public static class Strings
{
    private static global::System.Resources.ResourceManager? _resourceManager;

    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (_resourceManager is null)
                _resourceManager = new global::System.Resources.ResourceManager("SSHTunnel4Win.Resources.Strings", typeof(Strings).Assembly);
            return _resourceManager;
        }
    }

    public static string About => ResourceManager.GetString("About") ?? "";
    public static string AddDirective => ResourceManager.GetString("AddDirective") ?? "";
    public static string AddHost => ResourceManager.GetString("AddHost") ?? "";
    public static string AddRule => ResourceManager.GetString("AddRule") ?? "";
    public static string AddTunnel => ResourceManager.GetString("AddTunnel") ?? "";
    public static string AddTunnelHint => ResourceManager.GetString("AddTunnelHint") ?? "";
    public static string AdditionalSSHArguments => ResourceManager.GetString("AdditionalSSHArguments") ?? "";
    public static string Apply => ResourceManager.GetString("Apply") ?? "";
    public static string Authentication => ResourceManager.GetString("Authentication") ?? "";
    public static string AutoConnectOnLaunch => ResourceManager.GetString("AutoConnectOnLaunch") ?? "";
    public static string AutoReconnectOnDisconnect => ResourceManager.GetString("AutoReconnectOnDisconnect") ?? "";
    public static string BrowseBtn => ResourceManager.GetString("BrowseBtn") ?? "";
    public static string BuyMeACoffee => ResourceManager.GetString("BuyMeACoffee") ?? "";
    public static string Cancel => ResourceManager.GetString("Cancel") ?? "";
    public static string CheckForUpdates => ResourceManager.GetString("CheckForUpdates") ?? "";
    public static string CheckForUpdatesAutomatically => ResourceManager.GetString("CheckForUpdatesAutomatically") ?? "";
    public static string CheckNow => ResourceManager.GetString("CheckNow") ?? "";
    public static string Checking => ResourceManager.GetString("Checking") ?? "";
    public static string ClearLog => ResourceManager.GetString("ClearLog") ?? "";
    public static string Close => ResourceManager.GetString("Close") ?? "";
    public static string Command => ResourceManager.GetString("Command") ?? "";
    public static string Connect => ResourceManager.GetString("Connect") ?? "";
    public static string ConnectAnyway => ResourceManager.GetString("ConnectAnyway") ?? "";
    public static string Connected => ResourceManager.GetString("Connected") ?? "";
    public static string Connecting => ResourceManager.GetString("Connecting") ?? "";
    public static string Connection => ResourceManager.GetString("Connection") ?? "";
    public static string ConnectionLog => ResourceManager.GetString("ConnectionLog") ?? "";
    public static string Copied => ResourceManager.GetString("Copied") ?? "";
    public static string CopyFailed => ResourceManager.GetString("CopyFailed") ?? "";
    public static string CopyCLICommand => ResourceManager.GetString("CopyCLICommand") ?? "";
    public static string CopyLog => ResourceManager.GetString("CopyLog") ?? "";
    public static string CopyShareString => ResourceManager.GetString("CopyShareString") ?? "";
    public static string Delete => ResourceManager.GetString("Delete") ?? "";
    public static string Disconnect => ResourceManager.GetString("Disconnect") ?? "";
    public static string DisconnectAll => ResourceManager.GetString("DisconnectAll") ?? "";
    public static string DisconnectOnQuit => ResourceManager.GetString("DisconnectOnQuit") ?? "";
    public static string Disconnected => ResourceManager.GetString("Disconnected") ?? "";
    public static string Download => ResourceManager.GetString("Download") ?? "";
    public static string DownloadManually => ResourceManager.GetString("DownloadManually") ?? "";
    public static string EditAsText => ResourceManager.GetString("EditAsText") ?? "";
    public static string EnableDisable => ResourceManager.GetString("EnableDisable") ?? "";
    public static string Error => ResourceManager.GetString("Error") ?? "";
    public static string StartupError => ResourceManager.GetString("StartupError") ?? "";
    public static string File => ResourceManager.GetString("File") ?? "";
    public static string ForwardAgent => ResourceManager.GetString("ForwardAgent") ?? "";
    public static string General => ResourceManager.GetString("General") ?? "";
    public static string GitHub => ResourceManager.GetString("GitHub") ?? "";
    public static string Help => ResourceManager.GetString("Help") ?? "";
    public static string HelpAuthentication => ResourceManager.GetString("HelpAuthentication") ?? "";
    public static string HelpAuthDesc => ResourceManager.GetString("HelpAuthDesc") ?? "";
    public static string HelpDynamicDesc => ResourceManager.GetString("HelpDynamicDesc") ?? "";
    public static string HelpKeyboardShortcuts => ResourceManager.GetString("HelpKeyboardShortcuts") ?? "";
    public static string HelpKeyboardShortcutsDesc => ResourceManager.GetString("HelpKeyboardShortcutsDesc") ?? "";
    public static string HelpLocalDesc => ResourceManager.GetString("HelpLocalDesc") ?? "";
    public static string HelpMenuBar => ResourceManager.GetString("HelpMenuBar") ?? "";
    public static string HelpMenuBarDesc => ResourceManager.GetString("HelpMenuBarDesc") ?? "";
    public static string HelpRemoteDesc => ResourceManager.GetString("HelpRemoteDesc") ?? "";
    public static string HelpSSHConfig => ResourceManager.GetString("HelpSSHConfig") ?? "";
    public static string HelpSSHConfigDesc => ResourceManager.GetString("HelpSSHConfigDesc") ?? "";
    public static string HelpShareImport => ResourceManager.GetString("HelpShareImport") ?? "";
    public static string HelpShareImportDesc => ResourceManager.GetString("HelpShareImportDesc") ?? "";
    public static string HelpTunnelManagement => ResourceManager.GetString("HelpTunnelManagement") ?? "";
    public static string HelpTunnelManagementDesc => ResourceManager.GetString("HelpTunnelManagementDesc") ?? "";
    public static string HelpTunnelTypes => ResourceManager.GetString("HelpTunnelTypes") ?? "";
    public static string Host => ResourceManager.GetString("Host") ?? "";
    public static string HostName => ResourceManager.GetString("HostName") ?? "";
    public static string IdentityFile => ResourceManager.GetString("IdentityFile") ?? "";
    public static string Import => ResourceManager.GetString("Import") ?? "";
    public static string ImportFromShareString => ResourceManager.GetString("ImportFromShareString") ?? "";
    public static string ImportTunnelConfiguration => ResourceManager.GetString("ImportTunnelConfiguration") ?? "";
    public static string InstallAndRestart => ResourceManager.GetString("InstallAndRestart") ?? "";
    public static string Key => ResourceManager.GetString("Key") ?? "";
    public static string KillAll => ResourceManager.GetString("KillAll") ?? "";
    public static string KillProcess => ResourceManager.GetString("KillProcess") ?? "";
    public static string Later => ResourceManager.GetString("Later") ?? "";
    public static string LaunchAtLogin => ResourceManager.GetString("LaunchAtLogin") ?? "";
    public static string LoadFromSSHConfig => ResourceManager.GetString("LoadFromSSHConfig") ?? "";
    public static string LocalPort => ResourceManager.GetString("LocalPort") ?? "";
    public static string Method => ResourceManager.GetString("Method") ?? "";
    public static string MoveDown => ResourceManager.GetString("MoveDown") ?? "";
    public static string MoveUp => ResourceManager.GetString("MoveUp") ?? "";
    public static string Name => ResourceManager.GetString("Name") ?? "";
    public static string NewTunnel => ResourceManager.GetString("NewTunnel") ?? "";
    public static string NewVersionAvailable => ResourceManager.GetString("NewVersionAvailable") ?? "";
    public static string NoHostSelected => ResourceManager.GetString("NoHostSelected") ?? "";
    public static string NoHostsInConfig => ResourceManager.GetString("NoHostsInConfig") ?? "";
    public static string NoLogAvailable => ResourceManager.GetString("NoLogAvailable") ?? "";
    public static string NoProcesses => ResourceManager.GetString("NoProcesses") ?? "";
    public static string NoSSHConfigFound => ResourceManager.GetString("NoSSHConfigFound") ?? "";
    public static string NoTunnelSelected => ResourceManager.GetString("NoTunnelSelected") ?? "";
    public static string NoTunnels => ResourceManager.GetString("NoTunnels") ?? "";
    public static string OK => ResourceManager.GetString("OK") ?? "";
    public static string OpenInExternalEditor => ResourceManager.GetString("OpenInExternalEditor") ?? "";
    public static string OpenManager => ResourceManager.GetString("OpenManager") ?? "";
    public static string OpenManagerOnLaunch => ResourceManager.GetString("OpenManagerOnLaunch") ?? "";
    public static string OpenInEditor => ResourceManager.GetString("OpenInEditor") ?? "";
    public static string Options => ResourceManager.GetString("Options") ?? "";
    public static string OtherDirectives => ResourceManager.GetString("OtherDirectives") ?? "";
    public static string PID => ResourceManager.GetString("PID") ?? "";
    public static string Password => ResourceManager.GetString("Password") ?? "";
    public static string Port => ResourceManager.GetString("Port") ?? "";
    public static string PortConflict => ResourceManager.GetString("PortConflict") ?? "";
    public static string PortConflictMessage => ResourceManager.GetString("PortConflictMessage") ?? "";
    public static string PortForwarding => ResourceManager.GetString("PortForwarding") ?? "";
    public static string Preview => ResourceManager.GetString("Preview") ?? "";
    public static string Proxy => ResourceManager.GetString("Proxy") ?? "";
    public static string ProxyCommand => ResourceManager.GetString("ProxyCommand") ?? "";
    public static string ProxyJump => ResourceManager.GetString("ProxyJump") ?? "";
    public static string Quit => ResourceManager.GetString("Quit") ?? "";
    public static string Refresh => ResourceManager.GetString("Refresh") ?? "";
    public static string Reconnect => ResourceManager.GetString("Reconnect") ?? "";
    public static string ReconnectAll => ResourceManager.GetString("ReconnectAll") ?? "";
    public static string Reload => ResourceManager.GetString("Reload") ?? "";
    public static string RemoteHost => ResourceManager.GetString("RemoteHost") ?? "";
    public static string RemotePort => ResourceManager.GetString("RemotePort") ?? "";
    public static string RunningSSHProcesses => ResourceManager.GetString("RunningSSHProcesses") ?? "";
    public static string SSHConfig => ResourceManager.GetString("SSHConfig") ?? "";
    public static string SSHTunnelManager => ResourceManager.GetString("SSHTunnelManager") ?? "";
    public static string Search => ResourceManager.GetString("Search") ?? "";
    public static string SelectHostHint => ResourceManager.GetString("SelectHostHint") ?? "";
    public static string SelectTunnelHint => ResourceManager.GetString("SelectTunnelHint") ?? "";
    public static string ServerAliveCountMax => ResourceManager.GetString("ServerAliveCountMax") ?? "";
    public static string ServerAliveInterval => ResourceManager.GetString("ServerAliveInterval") ?? "";
    public static string Settings => ResourceManager.GetString("Settings") ?? "";
    public static string Share => ResourceManager.GetString("Share") ?? "";
    public static string Tunnels => ResourceManager.GetString("Tunnels") ?? "";
    public static string TunnelRules => ResourceManager.GetString("TunnelRules") ?? "";
    public static string TunnelTypeLocal => ResourceManager.GetString("TunnelTypeLocal") ?? "";
    public static string TunnelTypeRemote => ResourceManager.GetString("TunnelTypeRemote") ?? "";
    public static string TunnelTypeDynamic => ResourceManager.GetString("TunnelTypeDynamic") ?? "";
    public static string Type => ResourceManager.GetString("Type") ?? "";
    public static string UpToDate => ResourceManager.GetString("UpToDate") ?? "";
    public static string UpdateAvailable => ResourceManager.GetString("UpdateAvailable") ?? "";
    public static string UpdateFailed => ResourceManager.GetString("UpdateFailed") ?? "";
    public static string User => ResourceManager.GetString("User") ?? "";
    public static string Username => ResourceManager.GetString("Username") ?? "";
    public static string Value => ResourceManager.GetString("Value") ?? "";
    public static string Version => ResourceManager.GetString("Version") ?? "";
    public static string VersionAvailable => ResourceManager.GetString("VersionAvailable") ?? "";
}
